.PHONY: clean All

All:
	@echo "----------Building project:[ TestingForEquality - Debug ]----------"
	@cd "TestingForEquality" && "$(MAKE)" -f  "TestingForEquality.mk"
clean:
	@echo "----------Cleaning project:[ TestingForEquality - Debug ]----------"
	@cd "TestingForEquality" && "$(MAKE)" -f  "TestingForEquality.mk" clean
