.PHONY: clean All

All:
	@echo "----------Building project:[ Pennies - Debug ]----------"
	@cd "Pennies" && "$(MAKE)" -f  "Pennies.mk"
clean:
	@echo "----------Cleaning project:[ Pennies - Debug ]----------"
	@cd "Pennies" && "$(MAKE)" -f  "Pennies.mk" clean
