.PHONY: clean All

All:
	@echo "----------Building project:[ Graders - Debug ]----------"
	@cd "Graders" && "$(MAKE)" -f  "Graders.mk"
clean:
	@echo "----------Cleaning project:[ Graders - Debug ]----------"
	@cd "Graders" && "$(MAKE)" -f  "Graders.mk" clean
